#!/bin/sh

#
# usage: fixtabs file ...
# convert tabs to spaces and strip trailing whitespace
#
# example usage to fix all files that contain the VIM space-only modelines (expandtab):
# fixtabs `grep -l expandtab *`
#

for file in $*; do
	cp $file $file.tmp
	expand -4 <$file.tmp | perl -p -e 's/\s+\n$/\n/go;' >$file
	rm $file.tmp
done
